<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea__wpformsfields2</name>
   <tag></tag>
   <elementGuidId>add7f4be-757c-415e-b087-b24552a5308e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='wpforms-161-field_2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#wpforms-161-field_2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Comment or Message *&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>0924c8cd-0527-4d80-9816-fe9cb6068753</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wpforms-161-field_2</value>
      <webElementGuid>9782b5cd-9c68-4894-9c64-58831c4a0068</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wpforms-field-medium wpforms-field-required</value>
      <webElementGuid>5349af40-5e2a-4f95-98a6-0c47f6eb2228</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>wpforms[fields][2]</value>
      <webElementGuid>dbca3301-0869-414e-ac4e-eadbcd97bc03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wpforms-161-field_2&quot;)</value>
      <webElementGuid>7ff3f10e-3f0a-4eb0-a312-2143ac72048a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='wpforms-161-field_2']</value>
      <webElementGuid>be8ce8eb-9c24-43cd-b154-052c2106e895</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wpforms-161-field_2-container']/textarea</value>
      <webElementGuid>ee8ac773-c329-4d84-9fe6-1e7ad91344e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>7f8229a9-1837-423f-a3a3-3d6b5c9cc924</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'wpforms-161-field_2' and @name = 'wpforms[fields][2]']</value>
      <webElementGuid>f51523ad-012f-4570-add0-0852d5d50633</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
